require('dotenv').config();
const fs=require('fs'); const path=require('path');
const { runSingleCase }=require('./app'); const { ensureOutputDir }=require('./utils/outputContext'); const { upsertBatch, readStore, sanitize }=require('./utils/store');
const { refreshAnalytics }=require('./analytics');
const LOCK=path.join(ensureOutputDir(),'.morning.lock');
function batchCount(date=new Date()){ const weekday=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Kolkata',weekday:'long'}).format(date); return weekday==='Sunday'?10:3; }
function parseOptions(argv=process.argv.slice(2)){ const o={count:undefined,dryRun:false,youtubeOnly:false}; for(const arg of argv){if(arg.startsWith('--count='))o.count=Number(arg.slice(8));if(arg==='--dry-run')o.dryRun=true;if(arg==='--youtube-only')o.youtubeOnly=true;} if(o.count!==undefined&&(!Number.isInteger(o.count)||o.count<1))throw new Error('--count must be a positive integer.'); return o; }
function acquireLock(){ if(fs.existsSync(LOCK)){ const age=Date.now()-fs.statSync(LOCK).mtimeMs; if(age<12*60*60*1000) throw new Error('A morning batch is already running.'); fs.rmSync(LOCK,{force:true}); } fs.writeFileSync(LOCK,JSON.stringify({pid:process.pid,startedAt:new Date().toISOString()})); }
function releaseLock(){fs.rmSync(LOCK,{force:true});}
function report(batch){ const dir=path.join(ensureOutputDir(),'batches',batch.id);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'batch_report.json'),JSON.stringify(batch,null,2)); const lines=[`MidnightOS batch ${batch.id}`,`Started: ${batch.startedAt}`,`Ended: ${batch.completedAt||'in progress'}`,`Cases: ${batch.cases.length}/${batch.targetCount}`,''];for(const item of batch.cases)lines.push(`${item.caseId||'failed'}: ${(item.platforms||[]).map(p=>`${p.platform}=${p.uploaded?'success':p.error||'skipped'}`).join('; ')}`,item.error?`  Error: ${item.error}`:'');fs.writeFileSync(path.join(dir,'batch_report.txt'),lines.join('\n'),'utf8'); }
async function runMorning(options=parseOptions()){ acquireLock(); const target=options.count||batchCount(); const existing=Object.values(readStore().batches).find(b=>b.status==='running'&&b.targetCount===target); const batch=existing||{id:`batch-${new Date().toISOString().replace(/[:.]/g,'-')}`,startedAt:new Date().toISOString(),targetCount:target,cases:[],status:'running',options}; try { upsertBatch(batch);report(batch); for(let i=batch.cases.length;i<target;i+=1){console.log(`\nBatch ${i+1}/${target}\nGenerate`); const entry={startedAt:new Date().toISOString()};try{const output=await runSingleCase(options);entry.caseId=output.caseNumber;entry.outputDir=output.outputDir;entry.platforms=output.platforms;console.log('YouTube\nFacebook\nInstagram\nAnalytics');try { await refreshAnalytics(); } catch (_error) {} console.log('Complete');}catch(error){entry.error=sanitize(error.message);console.error(`Case failed: ${entry.error}`);}entry.completedAt=new Date().toISOString();batch.cases.push(entry);upsertBatch(batch);report(batch);} batch.status=batch.cases.some(c=>c.error)?'completed_with_errors':'completed';batch.completedAt=new Date().toISOString();upsertBatch(batch);report(batch);return batch;}finally{releaseLock();} }
if(require.main===module)runMorning().then(b=>console.log(`✅ Batch report: output/batches/${b.id}/batch_report.txt`)).catch(e=>{console.error(`❌ Morning batch failed: ${e.message}`);process.exitCode=1;});
module.exports={batchCount,parseOptions,acquireLock,releaseLock,runMorning,LOCK};
