const axios = require('axios');
const fs = require('fs');
const path = require('path');
const { publishYouTubeShorts } = require('./youtubePublisher');
const { retry } = require('./utils/retry');
const { validateVideo } = require('./utils/videoCompatibility');
function bool(name) { return String(process.env[name] || '').toLowerCase() === 'true'; }
function result(platform, fields={}) { return { platform, configured:true, attempted:false, uploaded:false, mediaId:null, url:null, error:null, startedAt:new Date().toISOString(), completedAt:null, ...fields }; }
function finish(r) { r.completedAt=new Date().toISOString(); return r; }
function metaConfig(platform) { const token=platform==='facebook'?process.env.FACEBOOK_PAGE_ACCESS_TOKEN:(process.env.INSTAGRAM_ACCESS_TOKEN || process.env.FACEBOOK_PAGE_ACCESS_TOKEN); const id=platform==='facebook'?process.env.FACEBOOK_PAGE_ID:process.env.INSTAGRAM_ACCOUNT_ID; const enabled=bool(platform==='facebook'?'FACEBOOK_UPLOAD_ENABLED':'INSTAGRAM_UPLOAD_ENABLED'); return { enabled, id, token, version:process.env.META_GRAPH_API_VERSION || 'v24.0' }; }
async function facebook(options) { const c=metaConfig('facebook'); if (!c.enabled || !c.id || !c.token) return finish(result('facebook',{configured:false, attempted:false, error:'Configuration required: FACEBOOK_UPLOAD_ENABLED, FACEBOOK_PAGE_ID, and FACEBOOK_PAGE_ACCESS_TOKEN.'})); const r=result('facebook'); if (options.dryRun) return finish({...r, attempted:true, error:'Dry run: Facebook upload not performed.'}); const compatibility=await validateVideo(options.videoPath, Number(process.env.FACEBOOK_MAX_DURATION_SECONDS)||undefined); if (!compatibility.valid) return finish({...r, attempted:false, error:`Video compatibility: ${compatibility.errors.join(' ')}`, compatibility}); try { const response=await retry(()=>axios.post(`https://graph.facebook.com/${c.version}/${c.id}/videos`, fs.createReadStream(options.videoPath), { headers:{ Authorization:`Bearer ${c.token}`, 'Content-Type':'video/mp4', 'Content-Length':fs.statSync(options.videoPath).size }, params:{ description:options.caption, published:true }, maxBodyLength:Infinity, timeout:120000 })); r.attempted=true; r.uploaded=Boolean(response.data?.id); r.mediaId=response.data?.id || null; r.url=r.mediaId ? `https://www.facebook.com/${r.mediaId}` : null; } catch (error) { r.attempted=true; r.error=`Facebook Graph API: ${error.response?.data?.error?.message || error.message}`; } return finish(r); }
async function instagram(options) { const c=metaConfig('instagram'); if (!c.enabled || !c.id || !c.token) return finish(result('instagram',{configured:false,error:'Configuration required: INSTAGRAM_UPLOAD_ENABLED, INSTAGRAM_ACCOUNT_ID, and INSTAGRAM_ACCESS_TOKEN (or Facebook Page token).'})); const url=options.publicVideoUrl; if (!url || !/^https:\/\//i.test(url)) return finish(result('instagram',{configured:false,error:'Configuration required: PUBLIC_MEDIA_BASE_URL or PUBLIC_MEDIA_STATIC_URL must provide a publicly reachable HTTPS video URL.'})); const r=result('instagram'); if (options.dryRun) return finish({...r,attempted:true,error:'Dry run: Instagram upload not performed.'}); try { const create=await retry(()=>axios.post(`https://graph.facebook.com/${c.version}/${c.id}/media`, null,{params:{access_token:c.token,media_type:'REELS',video_url:url,caption:options.caption,share_to_feed:true},timeout:30000})); const containerId=create.data.id; let status; for(let i=0;i<30;i+=1){ await new Promise((x)=>setTimeout(x,2000)); const poll=await axios.get(`https://graph.facebook.com/${c.version}/${containerId}`,{params:{fields:'status_code,status',access_token:c.token}}); status=poll.data.status_code || poll.data.status; if(status==='FINISHED') break; if(['ERROR','EXPIRED'].includes(status)) throw new Error(`Container status ${status}`); } if(status!=='FINISHED') throw new Error('Instagram container timed out.'); const published=await retry(()=>axios.post(`https://graph.facebook.com/${c.version}/${c.id}/media_publish`,null,{params:{access_token:c.token,creation_id:containerId}})); r.attempted=true;r.uploaded=Boolean(published.data.id);r.mediaId=published.data.id||null; if(r.mediaId){ const media=await axios.get(`https://graph.facebook.com/${c.version}/${r.mediaId}`,{params:{fields:'permalink',access_token:c.token}});r.url=media.data.permalink||null; } } catch(error){r.attempted=true;r.error=`Instagram Graph API: ${error.response?.data?.error?.message||error.message}`;} return finish(r); }
function publicUrl(videoPath) { if(process.env.PUBLIC_MEDIA_STATIC_URL) return process.env.PUBLIC_MEDIA_STATIC_URL; const base=process.env.PUBLIC_MEDIA_BASE_URL; const win = String(videoPath).includes('\\'); const basename = win ? path.win32.basename(videoPath) : path.basename(videoPath); const parent = win ? path.win32.basename(path.win32.dirname(videoPath)) : path.basename(path.dirname(videoPath)); return base ? `${base.replace(/\/$/,'')}/${encodeURIComponent(parent)}/${encodeURIComponent(basename)}` : null; }
async function youtube(options) { const r=result('youtube'); if(options.dryRun) return finish({...r,attempted:true,error:'Dry run: YouTube upload not performed.'}); try { const out=await publishYouTubeShorts({outputDir:options.outputDir,mode:'live'}); return finish({...r,attempted:true,uploaded:out.report.uploaded,mediaId:out.videoId||null,url:out.videoUrl||null}); } catch(error){return finish({...r,attempted:true,error:error.message});} }
async function publishAll(options) { const out=[]; if(options.youtubeOnly) out.push(await youtube(options)); else { out.push(await youtube(options)); out.push(await facebook(options)); out.push(await instagram({...options,publicVideoUrl:publicUrl(options.videoPath)})); } return out; }
module.exports={publishAll,facebook,instagram,youtube,publicUrl};
